exports.up = function (knex, Promise) {
  return knex.schema.createTable('tblScrChildren', (t) => {
    t.increments('scr_ch_id');
    t.integer('client_scr_ch_id');
    t.string('client_id');
    t.unique(['client_scr_ch_id', 'client_id']);
    t.integer('site_id')
    t.string('username');
    t.string('project');
    t.integer('upload_status').defaultTo(1);
    t.boolean('is_deleted');
    t.date('screening_date');
    t.string('village');
    t.string('staff_name');
    t.string('staff_code');
    t.string('sup_name');
    t.string('sup_code');
    t.integer('total_scr_girls');
    t.integer('total_scr_boys');
    t.integer('sam_without_comp_girls_623');
    t.integer('sam_without_comp_boys_623');
    t.integer('sam_without_comp_girls_2459');
    t.integer('sam_without_comp_boys_2459');
    t.integer('sam_with_comp_girls_623');
    t.integer('sam_with_comp_boys_623');
    t.integer('sam_with_comp_girls_2459');
    t.integer('sam_with_comp_boys_2459');
    t.integer('mam_boys_623');
    t.integer('mam_girls_623');
    t.integer('mam_boys_2459');
    t.integer('mam_girls_2459');
    t.integer('reffer_tsfp_girls');
    t.integer('reffer_tsfp_boys');
    t.integer('reffer_otp_girls');
    t.integer('reffer_otp_boys');
    t.integer('normal_girls_623');
    t.integer('normal_boys_623');
    t.integer('normal_girls_2459');
    t.integer('normal_boys_2459');
    t.integer('new_girls');
    t.integer('new_boys');
    t.integer('reScreened_girls');
    t.integer('reScreened_boys');
    t.integer('first_mnp_30_girls');
    t.integer('first_mnp_30_boys');
    t.integer('second_mnp_30_girls');
    t.integer('second_mnp_30_boys');
    t.integer('third_mnp_30_girls');
    t.integer('third_mnp_30_boys');
    t.integer('fourth_mnp_30_girls');
    t.integer('fourth_mnp_30_boys');
    t.integer('fifth_mnp_30_girls');
    t.integer('fifth_mnp_30_boys');
    t.integer('sixth_mnp_30_girls');
    t.integer('sixth_mnp_30_boys');
    t.integer('deworming_girls');
    t.integer('deworming_boys');
    t.integer('no_oedema_girls');
    t.integer('no_oedema_boys');
    t.integer('plus12_oedema_girls');
    t.integer('plus12_oedema_boys');
    t.integer('plus3_oedema_girls');
    t.integer('plus3_oedema_boys');
    t.string('report_month',10);
    t.integer('followedup_boys');
    t.integer('followedup_girls');
    t.integer('exits_boys');
    t.integer('exits_girls');
    t.string('other_specify');
    t.integer('other_boys');
    t.integer('other_girls');
    t.timestamp('created_at').defaultTo(knex.fn.now());
    t.timestamp('updated_at').defaultTo(knex.fn.now());
    t.boolean('isActive').defaultTo(true);
    t.integer('approved');
    t.date('upload_date');
    t.integer('catchment_population');
    t.string('site_one', 50);
    t.string('site_two', 50);
    t.integer('reffer_otp_girls_s1').defaultTo(0);
    t.integer('reffer_otp_girls_s2').defaultTo(0);
    t.integer('reffer_otp_boys_s1').defaultTo(0);
    t.integer('reffer_otp_boys_s2').defaultTo(0);
    t.integer('reffer_tsfp_boys_s1').defaultTo(0);
    t.integer('reffer_tsfp_boys_s2').defaultTo(0);
    t.integer('reffer_tsfp_girls_s1').defaultTo(0);
    t.integer('reffer_tsfp_girls_s2').defaultTo(0);
    t.integer('uc_id');
    t.integer('total_hh').defaultTo(0);
  })
};

exports.down = function (knex, Promise) {
  return knex.schema.dropTable('tblScrChildren');
};
exports.config = { transaction: false };