select (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND muac < 11.5 AND screening_type = 1) as childMBelow115Active,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND muac < 11.5 AND screening_type = 1) as childFBelow115Active,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND muac < 11.5 AND screening_type = 0) as childMBelow115Passive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND muac < 11.5 AND screening_type = 0) as childFBelow115Passive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND screening_type = 1 AND muac BETWEEN 11.499 AND 12.4) as childMBet115125Active,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND screening_type = 1 AND muac BETWEEN 11.499 AND 12.4) as childFBet115125Active,
  (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND screening_type = 0 AND muac BETWEEN 11.499 AND 12.4) as childMBet115125Passive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND screening_type = 0 AND muac BETWEEN 11.499 AND 12.4) as childFBet115125Passive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND screening_type = 1) as childMScrActive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND screening_type = 1) as childFScrActive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 1 AND screening_type = 1) as childMScrPassive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND gender = 2 AND screening_type = 1) as childFScrPassive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 1 AND screening_type = 1 AND screening_type = 1) as plwPScrActive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 2 AND screening_type = 1 AND screening_type = 1) as plwLScrActive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 1 AND screening_type = 1 AND screening_type = 0) as plwPScrPassive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 2 AND screening_type = 1 AND screening_type = 0) as plwLScrPassive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 1 AND screening_type = 1 AND screening_type = 1 AND muac < 21) as plwPBelow21Active,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 2 AND screening_type = 1 AND screening_type = 1 AND muac < 21) as plwLBelow21Active,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 1 AND screening_type = 1 AND screening_type = 0 AND muac < 21) as plwPBelowPassive,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND plw_type = 2 AND screening_type = 1 AND screening_type = 0 AND muac < 21) as plwLBelowPassive,
  (select COUNT(Screening.screening_id) from Screening where is_plw = 0) as childScr,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND muac <11.5) as childBelow115,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 0 AND muac between 11.5 and 12.4) as child115124,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1) as plwScr,
 (select COUNT(Screening.screening_id) from Screening where is_plw = 1 AND muac <21) as plwBelow21;